name: Run Mockito Unit Tests for RetailPro

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-retailpro:
    name: Test RetailPro with Mockito
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Set up SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build RetailPro project
        run: mvn -f pom.xml clean test
